# Materi

Fungsi

**cut**

Mengelompokkan data numeric ke dalam beberapa bin/interval
dengan menentukan berapa banyaknya bin yang diinginkan
dengan panjang masing-masing bin sama atau apa batas-batas
dari bins yang diinginkan

pd.cut(df['column_name'], bins,
label=lable_array, include_lowest=True)

**qcut**

Mengelompokkan data numeric ke dalam beberapa bin/interval
dengan menentukan berapa banyaknya bin yang diinginkan
dengan anggota setiap bin berjumlah sama (panjang
masing-masing bin bisa berbeda)

pd.qcut(df['column_name' ], q=num_of_bins,
label=lable_array)

* Binning dengan banyaknya bins tertentu
dan panjang masing-masing bin sama

Kolom usia berisi bilangan 0 sampai 70
tahun dikelompokkan ke dalam 4 bins
dengan panjang masing-masing bin sama

bins = np.linspace (min (df['age']),
max (df ['age' ]), 5)
pd.cut(df['age'], bins,
labels=category,
include_lowest=True)

* Binning dengan panjang masing-masing
interval tertentu

Kolom usia berisi bilangan 0 sampai 70
tahun dikelompokkan ke dalam bins dengan
panjang masing-masing bin 10 tahun

interval_range =
pd.interval_range(start=0,
freq=10, end=70)
pd.cut (df ['age' ],
bins=interval_range,
include_lowest=True)

A. Binning dengan panjang masing-masing
bin yang ditentukan sendiri sesuai
kebutuhan

Kolom usia berisi bilangan 0 sampai 70
tahun dikelompokkan ke dalam beberapa
bins dengan interval:
* 0-5 tahun: Balita
* 6-17 tahun: Kanak-Kanak
* 18-22 tahun: Remaja
* 23-44 tahun: Dewasa Muda
* 45-60 tahun: Dewasa
* 60+ tahun: Lanjut Usia

bins_edges = [0,5,17, 22, 44, 60, 70]
pd.cut(df['age'], bins,
labels=category,
include_lowest=True)

B. Binning dengan banyaknya bins tertentu
dan banyaknya anggota setiap bin relatif
sama

Kolom harga berisi bilangan 1000 sampai
500000 dikelompokkan ke dalam 3 bins
dengan banyaknya anggota ketiga bins
tersebut relatif sama

pd.qcut(df['price'], q=3,
labels=category)

# Impor packages

In [ ]:
# pip install pandas
# pip install numpy
import pandas as pd
import numpy as np

In [ ]:
import os
os.getcwd()

'/content'

# Impor data dari CSV ke DataFrame

In [ ]:
df = pd.read_csv('Online Retail Data.csv', header=0)
#mengasih batasan untuk data yang digunakan
df = df[df['price'].between(0, 100, inclusive='right')].reset_index(drop=True)
df

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457471 entries, 0 to 457470
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      457471 non-null  object
 1   product_code  457471 non-null  object
 2   product_name  457471 non-null  object
 3   quantity      457471 non-null  int64
 4   order_date    457471 non-null  object
 5   price         457471 non-null  float64
 6   customer_id   360613 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 24.4+ MB

# Membuat data binning di DataFrame

## Binning dengan banyaknya bins tertentu dan panjang masing-masing bin sama

In [ ]:
#pengelompokan dari 3 bin berdasarkan harga mengguanakan pandas otomatis
df1 = df.copy()
category = ['Cheap','Medium','Expensive']
df1['bin1'] = pd.cut(df1['price'], 3, labels=category, include_lowest=True)
df1

,order_id,product_code,product_name,quantity,order_date,price,customer_id,bin1
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Cheap
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Cheap
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Cheap
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Cheap
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Cheap
...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Cheap
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Cheap
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Cheap
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Cheap
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Cheap

In [ ]:
# mencari tahu pengolongannya
bin1_summary = df1.groupby('bin1').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))
bin1_summary['bin_interval'] = bin1_summary['max_price'] - bin1_summary['min_price']
bin1_summary

/tmp/ipykernel_1436/2461830182.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bin1_summary = df1.groupby('bin1').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))

           row_cnt  min_price  max_price  bin_interval
bin1
Cheap       456454      0.001      33.32        33.319
Medium         802     33.360      66.17        32.810
Expensive      215     66.770     100.00        33.230

In [ ]:
# menentukan 4 interval berdasarkan np.linspace
df2 = df1.copy()
bins = np.linspace(min(df['price']), max(df['price']), 4)
category = ['Cheap','Medium','Expensive']
df2['bin2'] = pd.cut(df2['price'], bins, labels=category, include_lowest=True)
df2

,order_id,product_code,product_name,quantity,order_date,price,customer_id,bin1,bin2
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Cheap,Cheap
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Cheap,Cheap
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Cheap,Cheap
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Cheap,Cheap
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Cheap,Cheap
...,...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Cheap,Cheap
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Cheap,Cheap
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Cheap,Cheap
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Cheap,Cheap
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Cheap,Cheap

In [ ]:
bins

array([1.0000e-03, 3.3334e+01, 6.6667e+01, 1.0000e+02])

In [ ]:
# mencari tahu pengolongannya
bin2_summary = df2.groupby('bin2').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))
bin2_summary['bin_interval'] = bin2_summary['max_price'] - bin2_summary['min_price']
bin2_summary

/tmp/ipykernel_1436/1722246105.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bin2_summary = df2.groupby('bin2').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))

           row_cnt  min_price  max_price  bin_interval
bin2
Cheap       456454      0.001      33.32        33.319
Medium         802     33.360      66.17        32.810
Expensive      215     66.770     100.00        33.230

## Binning dengan panjang masing-masing interval tertentu

In [ ]:
# menentukan intervalnya berdasarkan tentuan min max harganya dengan pembagian 10 frequensi
df3 = df2.copy()
interval_range = pd.interval_range(start=min(df['price']), freq=10, end=max(df['price']))
df3['bin3'] = pd.cut(df['price'], bins=interval_range, include_lowest=True)
df3

,order_id,product_code,product_name,quantity,order_date,price,customer_id,bin1,bin2,bin3
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Cheap,Cheap,"(0.001, 10.001]"
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Cheap,Cheap,"(0.001, 10.001]"
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Cheap,Cheap,"(0.001, 10.001]"
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Cheap,Cheap,"(0.001, 10.001]"
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Cheap,Cheap,"(0.001, 10.001]"
...,...,...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Cheap,Cheap,"(0.001, 10.001]"
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Cheap,Cheap,"(0.001, 10.001]"
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Cheap,Cheap,"(0.001, 10.001]"
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Cheap,Cheap,"(0.001, 10.001]"
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Cheap,Cheap,"(0.001, 10.001]"

In [ ]:
# melihat interval rangenya
interval_range

IntervalIndex([  (0.001, 10.001],  (10.001, 20.001],  (20.001, 30.001],
                (30.001, 40.001],  (40.001, 50.001],  (50.001, 60.001],
                (60.001, 70.001],  (70.001, 80.001],  (80.001, 90.001],
               (90.001, 100.001]],
              dtype='interval[float64, right]')

In [ ]:
# mencari tahu pengolongannya yang telah di tentukan dari freq sebanyak 10 sehingga binsnya menarik otomatis intervalnya sebanyak 10 gap, dilihat dari max pricenya
bin3_summary = df3.groupby('bin3').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))
bin3_summary['bin_interval'] = bin3_summary['max_price'] - bin3_summary['min_price']
bin3_summary

/tmp/ipykernel_1436/2073976978.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bin3_summary = df3.groupby('bin3').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))

                   row_cnt  min_price  max_price  bin_interval
bin3
(0.001, 10.001]     434969       0.01      10.00          9.99
(10.001, 20.001]     18806      10.04      20.00          9.96
(20.001, 30.001]      2609      20.13      30.00          9.87
(30.001, 40.001]       575      30.09      40.00          9.91
(40.001, 50.001]       177      40.04      50.00          9.96
(50.001, 60.001]        81      50.04      60.00          9.96
(60.001, 70.001]        49      60.21      70.00          9.79
(70.001, 80.001]       119      70.13      79.95          9.82
(80.001, 90.001]        31      80.70      90.00          9.30
(90.001, 100.001]       42      90.87     100.00          9.13

## Binning dengan panjang masing-masing bin yang ditentukan sendiri sesuai kebutuhan

In [ ]:
# kita melakukan intervalnya sebanyak 3 dengan penentuan dari kita dengan pengcategoriannya sebanyak 3
df4 = df3.copy()
bins_edges = [0, 30, 80, 100]
category = ['Cheap','Medium','Expensive']
df4['bin4'] = pd.cut(df['price'], bins=bins_edges, labels=category, include_lowest=True)
df4

,order_id,product_code,product_name,quantity,order_date,price,customer_id,bin1,bin2,bin3,bin4
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Cheap,Cheap,"(0.001, 10.001]",Cheap
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Cheap,Cheap,"(0.001, 10.001]",Cheap
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Cheap,Cheap,"(0.001, 10.001]",Cheap
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap
...,...,...,...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap

In [ ]:
# melihat jarak masing2 interval yang berbeda2 sesui dengan pendevinisian yang kita buat
bin4_summary = df4.groupby('bin4').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))
bin4_summary['bin_interval'] = bin4_summary['max_price'] - bin4_summary['min_price']
bin4_summary

/tmp/ipykernel_1436/3019213921.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bin4_summary = df4.groupby('bin4').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))

           row_cnt  min_price  max_price  bin_interval
bin4
Cheap       456397      0.001      30.00        29.999
Medium        1001     30.090      79.95        49.860
Expensive       73     80.700     100.00        19.300

## Binning dengan banyaknya bins tertentu dan banyaknya anggota setiap bin sama

In [ ]:
# membuat beans dengan paling simple karna kita mendevinisikan hanya 3 kategori dengan panjang intervalnya di tentukan sistem
df5 = df4.copy()
category = ['Cheap','Medium','Expensive']
df5['bin5'] = pd.qcut(df['price'], q=3, labels=category)
df5

,order_id,product_code,product_name,quantity,order_date,price,customer_id,bin1,bin2,bin3,bin4,bin5
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Cheap,Cheap,"(0.001, 10.001]",Cheap,Expensive
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Cheap,Cheap,"(0.001, 10.001]",Cheap,Expensive
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Cheap,Cheap,"(0.001, 10.001]",Cheap,Expensive
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Cheap
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Expensive
...,...,...,...,...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Cheap
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Cheap
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Expensive
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Cheap
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Medium

In [ ]:
# melihat summary bedasarkan intervalnya untuk melihat variasinya
bin5_summary = df5.groupby('bin5').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))
bin5_summary['bin_interval'] = bin5_summary['max_price'] - bin5_summary['min_price']
bin5_summary

/tmp/ipykernel_1436/2159517737.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bin5_summary = df5.groupby('bin5').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))

           row_cnt  min_price  max_price  bin_interval
bin5
Cheap       177438      0.001       1.65         1.649
Medium      135141      1.660       3.36         1.700
Expensive   144892      3.370     100.00        96.630

# Mengelompokkan data dengan case statement

In [ ]:
# melakukan pengelompokan berdasarkan kategiri produk yang telah kita tentukan menggunakan case statement
df6 = df5.copy()
df6['price_class'] = np.select(
    [(df6['product_name'].str.lower().str.contains('tea')) & (df6['price']<=2),
     (df6['product_name'].str.lower().str.contains('tea')) & (df6['price'].between(2, 4, inclusive='right')),
     (df6['product_name'].str.lower().str.contains('tea')) & (df6['price']>4),
     (df6['product_name'].str.lower().str.contains('coffee')) & (df6['price']<=3),
     (df6['product_name'].str.lower().str.contains('coffee')) & (df6['price'].between(3, 5, inclusive='right')),
     (df6['product_name'].str.lower().str.contains('coffee')) & (df6['price']>5)],
    ['Cheap Tea', 'Medium Tea', 'Expensive Tea', 'Cheap Coffee', 'Medium Coffee', 'Expensive Coffee'],
    default='Undetermined'
)
df6

,order_id,product_code,product_name,quantity,order_date,price,customer_id,bin1,bin2,bin3,bin4,bin5,price_class
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Cheap,Cheap,"(0.001, 10.001]",Cheap,Expensive,Undetermined
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Cheap,Cheap,"(0.001, 10.001]",Cheap,Expensive,Undetermined
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Cheap,Cheap,"(0.001, 10.001]",Cheap,Expensive,Undetermined
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Cheap,Undetermined
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Expensive,Undetermined
...,...,...,...,...,...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Cheap,Undetermined
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Cheap,Undetermined
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Expensive,Undetermined
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Cheap,Undetermined
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Cheap,Cheap,"(0.001, 10.001]",Cheap,Medium,Undetermined

In [ ]:
# melihat summarynya untuk melihat interval nya berdasarkan apa pengelompokkannya
price_class_summary = df6.groupby('price_class').agg(row_cnt=('product_code','count'), min_price=('price','min'), max_price=('price','max'))
price_class_summary['price_interval'] = price_class_summary['max_price'] - price_class_summary['min_price']
price_class_summary

                  row_cnt  min_price  max_price  price_interval
price_class
Cheap Coffee         1577      0.850       2.95           2.100
Cheap Tea            6149      0.080       2.00           1.920
Expensive Coffee      546      5.060      60.00          54.940
Expensive Tea        5954      4.140      29.74          25.600
Medium Coffee          86      3.360       4.30           0.940
Medium Tea           5160      2.090       4.00           1.910
Undetermined       437999      0.001     100.00          99.999