# Persiapan

In [ ]:
#mengimport library yang akan digunakan
import sqlite3
import pandas as pd

In [ ]:
#membuat koneksi
koneksi = sqlite3.connect('iowa_sales.db')

In [ ]:
#membuat kursor
kursor = koneksi.cursor()

# NO 1,2

In [ ]:
#Membuat variabel bernama "CekTabelDatabase" untuk mempermudah mengecek tabel yang ada di database iowa_sales
CekTabelDatabase = """
SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';

"""
kursor.execute(CekTabelDatabase)
pd.read_sql_query(CekTabelDatabase,koneksi)

       name
0  employee

In [ ]:
#Menghapus tabel employee
query = """ DROP TABLE employee;

"""

kursor.execute(query)

In [ ]:
#Mengecek kembali tabel yang ada di database iowa_sales
pd.read_sql_query(CekTabelDatabase,koneksi)

Empty DataFrame
Columns: [name]
Index: []

# NO 3

In [ ]:
#Membuat Tabel stock beserta kolomnya
query = """ CREATE TABLE stock (
  item_description VARCHAR (40) NOT NULL,
  stock_available INT NOT NULL,
  grade_rating FLOAT NOT NULL
);

"""
kursor.execute(query)

In [ ]:
#Membuat variabel bernama "DataTabelStock" untuk mempermudah melihat data pada Tabel stock
DataTabelStock = """ SELECT * FROM stock; """
kursor.execute(DataTabelStock)

In [ ]:
#Melihat data pada tabel stock
pd.read_sql_query(DataTabelStock,koneksi)

Empty DataFrame
Columns: [item_description, stock_available, grade_rating]
Index: []

In [ ]:
#Membuat variabel bernama "InfoTabelStock" untuk mempermudah dalam melihat struktur pada tabel stock
InfoTabelStock = """ PRAGMA table_info(stock); """
kursor.execute(InfoTabelStock)
pd.read_sql_query(InfoTabelStock,koneksi)

   cid              name          type  notnull dflt_value  pk
0    0  item_description  VARCHAR (40)        1       None   0
1    1   stock_available           INT        1       None   0
2    2      grade_rating         FLOAT        1       None   0

In [ ]:
#Memasukkan data pada tabel stock
query = """ INSERT INTO stock (item_description,stock_available,grade_rating)
VALUES
("JAGERMEISTER MINI MEISTERS",3437,3),
("MAKERS MARK W/HOLIDAY ORNAMENT",4821,5),
("CROWN ROYAL W/2 GLASSES",2095,4),
("BLACK VELVET TRAVELER",2731,5),
("CANADIAN RICH & RARE PEACH",1661,4),
("FOUR ROSES SMALL BATCH",1837,5),
("OLD FORESTER BOURBON 86 PRF",3990,5),
("TEN HIGH PET",1490,4),
("ABSOLUT APEACH",3451,5),
("FRIS DANISH VODKA",3033,4),
("WESTERN SON BLUEBERRY",1906,4),
("CRUZAN STRAWBERRY",1584,5),
("BAILEYS VANILLA CINNAMON",3025,5),
("KAHLUA COFFEE",4309,4),
("DEKUYPER LUSCIOUS PEACHTREE",3917,5)
;
"""

kursor.execute(query)

In [ ]:
#Melihat isi data pada tabel sales
pd.read_sql_query(DataTabelStock,koneksi)

                  item_description  stock_available  grade_rating
0       JAGERMEISTER MINI MEISTERS             3437           3.0
1   MAKERS MARK W/HOLIDAY ORNAMENT             4821           5.0
2          CROWN ROYAL W/2 GLASSES             2095           4.0
3            BLACK VELVET TRAVELER             2731           5.0
4       CANADIAN RICH & RARE PEACH             1661           4.0
5           FOUR ROSES SMALL BATCH             1837           5.0
6      OLD FORESTER BOURBON 86 PRF             3990           5.0
7                     TEN HIGH PET             1490           4.0
8                   ABSOLUT APEACH             3451           5.0
9                FRIS DANISH VODKA             3033           4.0
10           WESTERN SON BLUEBERRY             1906           4.0
11               CRUZAN STRAWBERRY             1584           5.0
12        BAILEYS VANILLA CINNAMON             3025           5.0
13                   KAHLUA COFFEE             4309           4.0
14     DEKUYPER LUSCIOUS PEACHTREE             3917           5.0

# NO 4

In [ ]:
#Mengimport data dari excel
ImportDataTabelSales = pd.read_excel('Iowa Liquor Sales - Praktik Mandiri 1 Modul 3.xlsx')

In [ ]:
#Memindahkan data excel ke sql
ImportDataTabelSales.to_sql('sales', koneksi, if_exists='replace')

1000

# NO 5

In [ ]:
#Membuat variabel bernama "DataTableSales" untuk mempermudah melihat isi data pada tabel sales
DataTabelSales = """ SELECT * FROM sales;"""
kursor.execute(DataTabelSales)
pd.read_sql_query(DataTabelSales,koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars
0,0,5052,CASEY'S GENERAL STORE #3220 / GREENF,GREENFIELD,1,ADAIR,SPICED RUM,43025,ADMIRAL NELSON SPICED RUM PET,12,750,6.00,9.00,24,216.00
1,1,4317,FAREWAY STORES #941 / GREENFIELD,GREENFIELD,1,ADAIR,CANADIAN WHISKIES,10550,BLACK VELVET TOASTED CARAMEL,12,750,6.75,10.13,24,243.12
2,2,5052,CASEY'S GENERAL STORE #3220 / GREENF,GREENFIELD,1,ADAIR,CANADIAN WHISKIES,11786,BLACK VELVET TRAVELER,12,750,5.23,7.85,24,188.40
3,3,4472,QUICK SHOP FOODS / CENTERVILLE,CENTERVILLE,4,APPANOOSE,CANADIAN WHISKIES,11776,BLACK VELVET,12,750,5.23,7.85,24,188.40
4,4,4419,KUM & GO #4 / LAMONI,LAMONI,27,DECATUR,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER MINI MEISTERS,12,20,4.93,7.40,1,7.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,3722,WAL-MART 1361 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,78293,SMIRNOFF PEACH LEMONADE,12,750,8.25,12.38,24,297.12
996,996,4197,FAREWAY STORES #014 / SERGEANT BLUFF,SERGEANT BLUFF,97,WOODBURY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00
997,997,2621,HY-VEE FOOD STORE #3 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00
998,998,5388,KUM & GO #119/ NORTHWOOD,NORTHWOOD,98,WORTH,STRAIGHT BOURBON WHISKIES,17086,BULLEIT BOURBON,12,750,16.50,24.75,24,594.00
999,999,5287,YESWAY STORE # 1029/ CLARION,CLARION,99,WRIGHT,AMERICAN VODKAS,36305,HAWKEYE VODKA PET,12,750,3.34,5.01,24,120.24

In [ ]:
#Melihat Variabel bernama "InfoTabelSales" untuk mempermudah melihat struktur dari tabel sales
InfoTabelSales = """ PRAGMA table_info(sales); """
kursor.execute(InfoTabelSales)
pd.read_sql_query(InfoTabelSales,koneksi)

    cid                 name     type  notnull dflt_value  pk
0     0                index  INTEGER        0       None   0
1     1         store_number  INTEGER        0       None   0
2     2           store_name     TEXT        0       None   0
3     3                 city     TEXT        0       None   0
4     4        county_number  INTEGER        0       None   0
5     5               county     TEXT        0       None   0
6     6        category_name     TEXT        0       None   0
7     7          item_number  INTEGER        0       None   0
8     8     item_description     TEXT        0       None   0
9     9                 pack  INTEGER        0       None   0
10   10     bottle_volume_ml  INTEGER        0       None   0
11   11    state_bottle_cost     REAL        0       None   0
12   12  state_bottle_retail     REAL        0       None   0
13   13         bottles_sold  INTEGER        0       None   0
14   14         sale_dollars     REAL        0       None   0

In [ ]:
#Mengecek tabel yang ada pada database
pd.read_sql_query(CekTabelDatabase,koneksi)

    name
0  stock
1  sales

In [ ]:
#Menambahkan kolom rating pada tabel sales
query = """ALTER TABLE sales
ADD COLUMN
rating FLOAT ;"""

kursor.execute(query)
pd.read_sql_query(DataTabelSales,koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,0,5052,CASEY'S GENERAL STORE #3220 / GREENF,GREENFIELD,1,ADAIR,SPICED RUM,43025,ADMIRAL NELSON SPICED RUM PET,12,750,6.00,9.00,24,216.00,None
1,1,4317,FAREWAY STORES #941 / GREENFIELD,GREENFIELD,1,ADAIR,CANADIAN WHISKIES,10550,BLACK VELVET TOASTED CARAMEL,12,750,6.75,10.13,24,243.12,None
2,2,5052,CASEY'S GENERAL STORE #3220 / GREENF,GREENFIELD,1,ADAIR,CANADIAN WHISKIES,11786,BLACK VELVET TRAVELER,12,750,5.23,7.85,24,188.40,None
3,3,4472,QUICK SHOP FOODS / CENTERVILLE,CENTERVILLE,4,APPANOOSE,CANADIAN WHISKIES,11776,BLACK VELVET,12,750,5.23,7.85,24,188.40,None
4,4,4419,KUM & GO #4 / LAMONI,LAMONI,27,DECATUR,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER MINI MEISTERS,12,20,4.93,7.40,1,7.40,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,3722,WAL-MART 1361 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,78293,SMIRNOFF PEACH LEMONADE,12,750,8.25,12.38,24,297.12,None
996,996,4197,FAREWAY STORES #014 / SERGEANT BLUFF,SERGEANT BLUFF,97,WOODBURY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
997,997,2621,HY-VEE FOOD STORE #3 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
998,998,5388,KUM & GO #119/ NORTHWOOD,NORTHWOOD,98,WORTH,STRAIGHT BOURBON WHISKIES,17086,BULLEIT BOURBON,12,750,16.50,24.75,24,594.00,None
999,999,5287,YESWAY STORE # 1029/ CLARION,CLARION,99,WRIGHT,AMERICAN VODKAS,36305,HAWKEYE VODKA PET,12,750,3.34,5.01,24,120.24,None

In [ ]:
#Mengecek apakah ada kolom rating pada tabel sales
pd.read_sql_query(InfoTabelSales,koneksi)

    cid                 name     type  notnull dflt_value  pk
0     0                index  INTEGER        0       None   0
1     1         store_number  INTEGER        0       None   0
2     2           store_name     TEXT        0       None   0
3     3                 city     TEXT        0       None   0
4     4        county_number  INTEGER        0       None   0
5     5               county     TEXT        0       None   0
6     6        category_name     TEXT        0       None   0
7     7          item_number  INTEGER        0       None   0
8     8     item_description     TEXT        0       None   0
9     9                 pack  INTEGER        0       None   0
10   10     bottle_volume_ml  INTEGER        0       None   0
11   11    state_bottle_cost     REAL        0       None   0
12   12  state_bottle_retail     REAL        0       None   0
13   13         bottles_sold  INTEGER        0       None   0
14   14         sale_dollars     REAL        0       None   0
15   15               rating    FLOAT        0       None   0

# NO 6

# NO 6.1

In [ ]:
#Mengecek Data pada tabel sales dengan catagory_name nya "CREAM LIQUEURS"
query = """ SELECT * FROM sales WHERE category_name ="CREAM LIQUEURS" ;"""

kursor.execute(query)
pd.read_sql_query(query,koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,127,2515,HY-VEE FOOD STORE #1 / MASON CITY,MASON CITY,17,CERRO GORDO,CREAM LIQUEURS,68049,BAILEYS VANILLA CINNAMON,12,750,13.00,19.50,24,468.00,None
1,177,4204,FAREWAY STORES #025 / CLINTON,CLINTON,23,CLINTON,CREAM LIQUEURS,73055,RUMCHATA,12,750,12.50,18.75,24,450.00,None
2,279,2558,HY-VEE FOOD STORE / MOUNT PLEASANT,MOUNT PLEASANT,44,HENRY,CREAM LIQUEURS,68022,BAILEYS SALTED CARAMEL,12,750,13.50,20.25,24,486.00,None
3,360,2584,HY-VEE FOOD STORE / FORT MADISON,FORT MADISON,56,LEE,CREAM LIQUEURS,68011,BAILEYS STRAWBERRIES & CREAM,12,750,13.00,19.50,24,468.00,None
4,370,3549,QUICKER LIQUOR STORE,FORT MADISON,56,LEE,CREAM LIQUEURS,73055,RUMCHATA,12,750,13.00,19.50,24,468.00,None
5,372,2590,HY-VEE FOOD STORE #5 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,CREAM LIQUEURS,68036,BAILEYS ORIGINAL IRISH CREAM,12,750,16.49,24.74,24,593.76,None
6,373,2569,HY-VEE FOOD STORE #2 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,CREAM LIQUEURS,68036,BAILEYS ORIGINAL IRISH CREAM,12,750,16.49,24.74,24,593.76,None
7,482,2566,HY-VEE FOOD STORE / KNOXVILLE,KNOXVILLE,63,MARION,CREAM LIQUEURS,73055,RUMCHATA,12,750,13.50,20.25,24,486.00,None
8,518,5127,PRICE CHOPPER / INGERSOLL,DES MOINES,77,POLK,CREAM LIQUEURS,67902,BAILEYS DELICIOUSLY LIGHT,12,750,16.49,24.74,24,593.76,None
9,711,4829,CENTRAL CITY 2,DES MOINES,77,POLK,CREAM LIQUEURS,73055,RUMCHATA,12,750,13.00,19.50,24,450.00,None
10,712,4829,CENTRAL CITY 2,DES MOINES,77,POLK,CREAM LIQUEURS,73055,RUMCHATA,12,750,13.50,20.25,24,486.00,None
11,713,4829,CENTRAL CITY 2,DES MOINES,77,POLK,CREAM LIQUEURS,73055,RUMCHATA,12,750,13.00,19.50,24,468.00,None
12,714,3644,WAL-MART 2764 / ALTOONA,ALTOONA,77,POLK,CREAM LIQUEURS,80456,RYANS CREAM LIQUEUR,12,750,6.70,10.05,24,193.44,None
13,768,2201,HAPPY'S WINE & SPIRITS WHOLESALE,CEDAR FALLS,7,BLACK HAWK,CREAM LIQUEURS,73053,RUMCHATA,6,1000,17.00,25.50,18,459.00,None
14,826,3952,LOT-A-SPIRITS,BETTENDORF,82,SCOTT,CREAM LIQUEURS,80236,IOWISH CREAM LIQUEUR,6,750,10.17,15.26,24,366.24,None
15,861,2603,HY-VEE WINE AND SPIRITS / BETTENDORF,BETTENDORF,82,SCOTT,CREAM LIQUEURS,73055,RUMCHATA,12,750,13.50,20.25,24,486.00,None
16,922,2596,HY-VEE / REGAL LIQUORS AND VIDEO,OTTUMWA,90,WAPELLO,CREAM LIQUEURS,68846,ST BRENDANS IRISH CREAM,12,750,7.69,11.54,24,276.96,None
17,993,3722,WAL-MART 1361 / SIOUX CITY,SIOUX CITY,97,WOODBURY,CREAM LIQUEURS,80456,RYAN'S CREAM LIQUEUR,12,750,6.70,10.05,24,241.20,None

In [ ]:
#Mengubah data pack yang ada pada tabel sales dengan data category_name nya = "CREAM LIQUEURS"
query = """ UPDATE sales
SET pack = 40 WHERE category_name="CREAM LIQUEURS";"""

kursor.execute(query)

In [ ]:
#Mengecek lagi data pada tabel sales yang sudah dilakukan perubahan pack menjadi 40 dengan kententuan category_name nya ="CREAM LIQUEURS"
pd.read_sql_query("""SELECT * FROM sales WHERE category_name ="CREAM LIQUEURS";""", koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,127,2515,HY-VEE FOOD STORE #1 / MASON CITY,MASON CITY,17,CERRO GORDO,CREAM LIQUEURS,68049,BAILEYS VANILLA CINNAMON,40,750,13.00,19.50,24,468.00,None
1,177,4204,FAREWAY STORES #025 / CLINTON,CLINTON,23,CLINTON,CREAM LIQUEURS,73055,RUMCHATA,40,750,12.50,18.75,24,450.00,None
2,279,2558,HY-VEE FOOD STORE / MOUNT PLEASANT,MOUNT PLEASANT,44,HENRY,CREAM LIQUEURS,68022,BAILEYS SALTED CARAMEL,40,750,13.50,20.25,24,486.00,None
3,360,2584,HY-VEE FOOD STORE / FORT MADISON,FORT MADISON,56,LEE,CREAM LIQUEURS,68011,BAILEYS STRAWBERRIES & CREAM,40,750,13.00,19.50,24,468.00,None
4,370,3549,QUICKER LIQUOR STORE,FORT MADISON,56,LEE,CREAM LIQUEURS,73055,RUMCHATA,40,750,13.00,19.50,24,468.00,None
5,372,2590,HY-VEE FOOD STORE #5 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,CREAM LIQUEURS,68036,BAILEYS ORIGINAL IRISH CREAM,40,750,16.49,24.74,24,593.76,None
6,373,2569,HY-VEE FOOD STORE #2 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,CREAM LIQUEURS,68036,BAILEYS ORIGINAL IRISH CREAM,40,750,16.49,24.74,24,593.76,None
7,482,2566,HY-VEE FOOD STORE / KNOXVILLE,KNOXVILLE,63,MARION,CREAM LIQUEURS,73055,RUMCHATA,40,750,13.50,20.25,24,486.00,None
8,518,5127,PRICE CHOPPER / INGERSOLL,DES MOINES,77,POLK,CREAM LIQUEURS,67902,BAILEYS DELICIOUSLY LIGHT,40,750,16.49,24.74,24,593.76,None
9,711,4829,CENTRAL CITY 2,DES MOINES,77,POLK,CREAM LIQUEURS,73055,RUMCHATA,40,750,13.00,19.50,24,450.00,None
10,712,4829,CENTRAL CITY 2,DES MOINES,77,POLK,CREAM LIQUEURS,73055,RUMCHATA,40,750,13.50,20.25,24,486.00,None
11,713,4829,CENTRAL CITY 2,DES MOINES,77,POLK,CREAM LIQUEURS,73055,RUMCHATA,40,750,13.00,19.50,24,468.00,None
12,714,3644,WAL-MART 2764 / ALTOONA,ALTOONA,77,POLK,CREAM LIQUEURS,80456,RYANS CREAM LIQUEUR,40,750,6.70,10.05,24,193.44,None
13,768,2201,HAPPY'S WINE & SPIRITS WHOLESALE,CEDAR FALLS,7,BLACK HAWK,CREAM LIQUEURS,73053,RUMCHATA,40,1000,17.00,25.50,18,459.00,None
14,826,3952,LOT-A-SPIRITS,BETTENDORF,82,SCOTT,CREAM LIQUEURS,80236,IOWISH CREAM LIQUEUR,40,750,10.17,15.26,24,366.24,None
15,861,2603,HY-VEE WINE AND SPIRITS / BETTENDORF,BETTENDORF,82,SCOTT,CREAM LIQUEURS,73055,RUMCHATA,40,750,13.50,20.25,24,486.00,None
16,922,2596,HY-VEE / REGAL LIQUORS AND VIDEO,OTTUMWA,90,WAPELLO,CREAM LIQUEURS,68846,ST BRENDANS IRISH CREAM,40,750,7.69,11.54,24,276.96,None
17,993,3722,WAL-MART 1361 / SIOUX CITY,SIOUX CITY,97,WOODBURY,CREAM LIQUEURS,80456,RYAN'S CREAM LIQUEUR,40,750,6.70,10.05,24,241.20,None

# NO 6.2

In [ ]:
#Mengencek data pada tabel sales dengan ketentuan item_description "TITOS HANDMADE VODKA"
pd.read_sql_query("""SELECT * FROM sales where item_description="TITOS HANDMADE VODKA";""", koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,73,4147,FAREWAY STORES #974 / CEDAR FALLS,CEDAR FALLS,7,BLACK HAWK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
1,74,4988,HAPPY'S WINE & SPIRITS,CEDAR FALLS,7,BLACK HAWK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
2,92,3889,WAL-MART 1005 / WAVERLY,WAVERLY,9,BREMER,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
3,98,3859,WAL-MART 0750 / INDEPENDENCE,INDEPENDENCE,10,BUCHANAN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
4,122,3833,WAL-MART 3394 / ATLANTIC,ATLANTIC,15,CASS,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
5,147,3528,SUPER TARGET T-0804 MASON CITY,MASON CITY,17,CERRO GORDO,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
6,148,3528,SUPER TARGET T-0804 MASON CITY,MASON CITY,17,CERRO GORDO,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
7,149,5617,CASEY'S GENERAL STORE #2513 / NASHUA,NASHUA,19,CHICKASAW,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
8,180,2616,HY-VEE FOOD AND DRUG / CLINTON,CLINTON,23,CLINTON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
9,181,2616,HY-VEE FOOD AND DRUG / CLINTON,CLINTON,23,CLINTON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
10,182,2616,HY-VEE FOOD AND DRUG / CLINTON,CLINTON,23,CLINTON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
11,200,4137,FAREWAY STORES #989 / WAUKEE,WAUKEE,25,DALLAS,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
12,204,4019,WAL-MART 1506 / MANCHESTER,MANCHESTER,28,DELAWARE,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
13,217,4258,FAREWAY STORES #009 / BURLINGTON,BURLINGTON,29,DES MOINES,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
14,226,3622,WAL-MART 1415 / SPIRIT LAKE,SPIRIT LAKE,30,DICKINSON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
15,297,4051,FAREWAY STORES #639 / MAQUOKETA,MAQUOKETA,49,JACKSON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
16,298,3934,WAL-MART 1509 / MAQUOKETA,MAQUOKETA,49,JACKSON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
17,351,6041,DOWNTOWN LIQUOR / IOWA CITY,IOWA CITY,52,JOHNSON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
18,352,5039,CASEY'S GENERAL STORE #3384 / SOLON,SOLON,52,JOHNSON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
19,458,4856,BROTHERS MARKET / LISBON,LISBON,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
20,459,2568,HY-VEE FOOD STORE #4 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
21,460,5572,CASEY'S GENERAL STORE #2790 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
22,461,2569,HY-VEE FOOD STORE #2 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
23,462,4876,QUICK MART / HIAWATHA,HIAWATHA,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
24,463,2568,HY-VEE FOOD STORE #4 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
25,464,3707,TARGET STORE T-1768 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
26,465,4493,CASEY'S GENERAL STORE #2850 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
27,473,3789,WAL-MART 1393 / OSKALOOSA,OSKALOOSA,62,MAHASKA,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
28,505,2607,HY-VEE WINE AND SPIRITS / SHENANDOAH,SHENANDOAH,73,PAGE,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
29,733,2619,HY-VEE WINE AND SPIRITS / WDM,WEST DES MOINES,77,POLK,AMERICAN VODKAS,38174,TITOS HANDMADE VODKA,12,375,5.42,8.13,48,390.24,None
30,734,5127,PRICE CHOPPER / INGERSOLL,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
31,735,5917,URBANDALE LIQUOR,URBANDALE,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
32,736,3691,TARGET STORE T-1791 / URBANDALE,URBANDALE,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
33,737,3644,WAL-MART 2764 / ALTOONA,ALTOONA,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
34,738,4802,WALGREENS #07452 / DES MOINES,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
35,739,4131,FAREWAY STORES #933 / URBANDALE,URBANDALE,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
36,740,4405,KUM & GO #92 / ANKENY,ANKENY,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
37,741,4301,SAHOTA FOOD MART,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
38,742,5127,PRICE CHOPPER / INGERSOLL,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
39,743,3870,TARGET STORE T-1939 / ALTOONA,ALTOONA,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
40,744,2528,HY-VEE FOOD STORE #3 / DES MOINES,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
41,745,5600,H & A MINI MART,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
42,788,3521,AMERISTAR CASINO / COUNCIL BLUFFS,COUNCIL BLUFFS,78,POTTAWATTAMIE,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
43,796,5150,CASEY'S GENERAL STORE #2815 / VICT,VICTOR,79,POWESHIEK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
44,864,3731,WAL-MART 1241 / DAVENPORT,DAVENPORT,82,SCOTT,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,347.04,None
45,865,4751,WALGREENS #03595 / DAVENPORT,DAVENPORT,82,SCOTT,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
46,908,4015,WAL-MART 0749 / AMES,AMES,85,STORY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
47,931,5050,FAREWAY STORES #147 / CARLISLE,CARLISLE,91,WARREN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
48,946,3901,TARGET STORE T-0878 / FORT DODGE,FORT DODGE,94,WEBSTER,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,347.04,None
49,996,4197,FAREWAY STORES #014 / SERGEANT BLUFF,SERGEANT BLUFF,97,WOODBURY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None
50,997,2621,HY-VEE FOOD STORE #3 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,360.00,None

In [ ]:
#Mengubah data pada kolom sale_dollars menjadi 400 dengan ketentuan item_descriptionnya "TITOS HANDMADE VODKA"
query = """ UPDATE sales
SET sale_dollars = 400 WHERE item_description="TITOS HANDMADE VODKA";"""

kursor.execute(query)

In [ ]:
#Mengecek lagi data pada tabel sales yang sudah diubah sale_dollarsnya dengan ketentuan item_description "TITOS HANDMADE VODKA"
pd.read_sql_query("""SELECT * FROM sales where item_description="TITOS HANDMADE VODKA";""",koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,73,4147,FAREWAY STORES #974 / CEDAR FALLS,CEDAR FALLS,7,BLACK HAWK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
1,74,4988,HAPPY'S WINE & SPIRITS,CEDAR FALLS,7,BLACK HAWK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
2,92,3889,WAL-MART 1005 / WAVERLY,WAVERLY,9,BREMER,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
3,98,3859,WAL-MART 0750 / INDEPENDENCE,INDEPENDENCE,10,BUCHANAN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
4,122,3833,WAL-MART 3394 / ATLANTIC,ATLANTIC,15,CASS,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
5,147,3528,SUPER TARGET T-0804 MASON CITY,MASON CITY,17,CERRO GORDO,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
6,148,3528,SUPER TARGET T-0804 MASON CITY,MASON CITY,17,CERRO GORDO,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
7,149,5617,CASEY'S GENERAL STORE #2513 / NASHUA,NASHUA,19,CHICKASAW,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
8,180,2616,HY-VEE FOOD AND DRUG / CLINTON,CLINTON,23,CLINTON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
9,181,2616,HY-VEE FOOD AND DRUG / CLINTON,CLINTON,23,CLINTON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
10,182,2616,HY-VEE FOOD AND DRUG / CLINTON,CLINTON,23,CLINTON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
11,200,4137,FAREWAY STORES #989 / WAUKEE,WAUKEE,25,DALLAS,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
12,204,4019,WAL-MART 1506 / MANCHESTER,MANCHESTER,28,DELAWARE,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
13,217,4258,FAREWAY STORES #009 / BURLINGTON,BURLINGTON,29,DES MOINES,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
14,226,3622,WAL-MART 1415 / SPIRIT LAKE,SPIRIT LAKE,30,DICKINSON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
15,297,4051,FAREWAY STORES #639 / MAQUOKETA,MAQUOKETA,49,JACKSON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
16,298,3934,WAL-MART 1509 / MAQUOKETA,MAQUOKETA,49,JACKSON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
17,351,6041,DOWNTOWN LIQUOR / IOWA CITY,IOWA CITY,52,JOHNSON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
18,352,5039,CASEY'S GENERAL STORE #3384 / SOLON,SOLON,52,JOHNSON,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
19,458,4856,BROTHERS MARKET / LISBON,LISBON,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
20,459,2568,HY-VEE FOOD STORE #4 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
21,460,5572,CASEY'S GENERAL STORE #2790 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
22,461,2569,HY-VEE FOOD STORE #2 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
23,462,4876,QUICK MART / HIAWATHA,HIAWATHA,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
24,463,2568,HY-VEE FOOD STORE #4 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
25,464,3707,TARGET STORE T-1768 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
26,465,4493,CASEY'S GENERAL STORE #2850 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
27,473,3789,WAL-MART 1393 / OSKALOOSA,OSKALOOSA,62,MAHASKA,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
28,505,2607,HY-VEE WINE AND SPIRITS / SHENANDOAH,SHENANDOAH,73,PAGE,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
29,733,2619,HY-VEE WINE AND SPIRITS / WDM,WEST DES MOINES,77,POLK,AMERICAN VODKAS,38174,TITOS HANDMADE VODKA,12,375,5.42,8.13,48,400.0,None
30,734,5127,PRICE CHOPPER / INGERSOLL,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
31,735,5917,URBANDALE LIQUOR,URBANDALE,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
32,736,3691,TARGET STORE T-1791 / URBANDALE,URBANDALE,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
33,737,3644,WAL-MART 2764 / ALTOONA,ALTOONA,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
34,738,4802,WALGREENS #07452 / DES MOINES,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
35,739,4131,FAREWAY STORES #933 / URBANDALE,URBANDALE,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
36,740,4405,KUM & GO #92 / ANKENY,ANKENY,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
37,741,4301,SAHOTA FOOD MART,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
38,742,5127,PRICE CHOPPER / INGERSOLL,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
39,743,3870,TARGET STORE T-1939 / ALTOONA,ALTOONA,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
40,744,2528,HY-VEE FOOD STORE #3 / DES MOINES,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
41,745,5600,H & A MINI MART,DES MOINES,77,POLK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
42,788,3521,AMERISTAR CASINO / COUNCIL BLUFFS,COUNCIL BLUFFS,78,POTTAWATTAMIE,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
43,796,5150,CASEY'S GENERAL STORE #2815 / VICT,VICTOR,79,POWESHIEK,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
44,864,3731,WAL-MART 1241 / DAVENPORT,DAVENPORT,82,SCOTT,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
45,865,4751,WALGREENS #03595 / DAVENPORT,DAVENPORT,82,SCOTT,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
46,908,4015,WAL-MART 0749 / AMES,AMES,85,STORY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
47,931,5050,FAREWAY STORES #147 / CARLISLE,CARLISLE,91,WARREN,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
48,946,3901,TARGET STORE T-0878 / FORT DODGE,FORT DODGE,94,WEBSTER,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,9.64,14.46,24,400.0,None
49,996,4197,FAREWAY STORES #014 / SERGEANT BLUFF,SERGEANT BLUFF,97,WOODBURY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None
50,997,2621,HY-VEE FOOD STORE #3 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.0,None

# NO 6.3

In [ ]:
#Mengecek tabel sales dengan ketentuan category_namenya "AMERICAN VODKAS"
pd.read_sql_query("""SELECT * FROM sales WHERE category_name="AMERICAN VODKAS";""",koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,5,5714,YESWAY #1031,CENTERVILLE,4,APPANOOSE,AMERICAN VODKAS,36304,HAWKEYE VODKA,24,375,1.86,2.79,48,133.92,None
1,30,5426,PRIME MART 2 / CEDAR FALLS,CEDAR FALLS,7,BLACK HAWK,AMERICAN VODKAS,35926,FIVE O'CLOCK PET VODKA,12,750,3.37,5.06,24,121.44,None
2,31,4959,BANI'S,CEDAR FALLS,7,BLACK HAWK,AMERICAN VODKAS,35916,FIVE O'CLOCK VODKA,12,750,3.37,5.06,24,121.44,None
3,33,5295,YESWAY STORE # 10023/ WATERLOO,WATERLOO,7,BLACK HAWK,AMERICAN VODKAS,36305,HAWKEYE VODKA,12,750,3.34,5.01,24,120.24,None
4,34,5941,PRIME MART - CEDAR FALLS,CEDAR FALLS,7,BLACK HAWK,AMERICAN VODKAS,36305,HAWKEYE VODKA PET,12,750,3.34,5.01,24,120.24,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,994,3722,WAL-MART 1361 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,37996,SMIRNOFF 80PRF,12,750,8.25,12.38,24,297.12,None
281,995,3722,WAL-MART 1361 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,78293,SMIRNOFF PEACH LEMONADE,12,750,8.25,12.38,24,297.12,None
282,996,4197,FAREWAY STORES #014 / SERGEANT BLUFF,SERGEANT BLUFF,97,WOODBURY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.00,None
283,997,2621,HY-VEE FOOD STORE #3 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,38176,TITOS HANDMADE VODKA,12,750,10.00,15.00,24,400.00,None
284,999,5287,YESWAY STORE # 1029/ CLARION,CLARION,99,WRIGHT,AMERICAN VODKAS,36305,HAWKEYE VODKA PET,12,750,3.34,5.01,24,120.24,None

In [ ]:
#Mengubah data item_description menjadi "MCCORMICK 80PRF VODKA" dengan ketentuan category_namenya "AMERICAN VODKAS"
query = """ UPDATE sales
SET item_description = "MCCORMICK 80PRF VODKA" WHERE category_name = "AMERICAN VODKAS";"""
kursor.execute(query)

In [ ]:
#Mengecek kembali data yang sudah diubah pada tabel sales dengan ketentuan category_namenya "AMERICAN VODKAS"
pd.read_sql_query("""SELECT * FROM sales WHERE category_name="AMERICAN VODKAS";""",koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,5,5714,YESWAY #1031,CENTERVILLE,4,APPANOOSE,AMERICAN VODKAS,36304,MCCORMICK 80PRF VODKA,24,375,1.86,2.79,48,133.92,None
1,30,5426,PRIME MART 2 / CEDAR FALLS,CEDAR FALLS,7,BLACK HAWK,AMERICAN VODKAS,35926,MCCORMICK 80PRF VODKA,12,750,3.37,5.06,24,121.44,None
2,31,4959,BANI'S,CEDAR FALLS,7,BLACK HAWK,AMERICAN VODKAS,35916,MCCORMICK 80PRF VODKA,12,750,3.37,5.06,24,121.44,None
3,33,5295,YESWAY STORE # 10023/ WATERLOO,WATERLOO,7,BLACK HAWK,AMERICAN VODKAS,36305,MCCORMICK 80PRF VODKA,12,750,3.34,5.01,24,120.24,None
4,34,5941,PRIME MART - CEDAR FALLS,CEDAR FALLS,7,BLACK HAWK,AMERICAN VODKAS,36305,MCCORMICK 80PRF VODKA,12,750,3.34,5.01,24,120.24,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,994,3722,WAL-MART 1361 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,37996,MCCORMICK 80PRF VODKA,12,750,8.25,12.38,24,297.12,None
281,995,3722,WAL-MART 1361 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,78293,MCCORMICK 80PRF VODKA,12,750,8.25,12.38,24,297.12,None
282,996,4197,FAREWAY STORES #014 / SERGEANT BLUFF,SERGEANT BLUFF,97,WOODBURY,AMERICAN VODKAS,38176,MCCORMICK 80PRF VODKA,12,750,10.00,15.00,24,400.00,None
283,997,2621,HY-VEE FOOD STORE #3 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,38176,MCCORMICK 80PRF VODKA,12,750,10.00,15.00,24,400.00,None
284,999,5287,YESWAY STORE # 1029/ CLARION,CLARION,99,WRIGHT,AMERICAN VODKAS,36305,MCCORMICK 80PRF VODKA,12,750,3.34,5.01,24,120.24,None

# NO 6.4

In [ ]:
#Mengecek data pada tabel sales dengan ketentuan bottles_soldnya kurang dari 20
pd.read_sql_query("""SELECT * FROM sales WHERE bottles_sold <20;""",koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,4,4419,KUM & GO #4 / LAMONI,LAMONI,27,DECATUR,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER MINI MEISTERS,12,20,4.93,7.40,1,7.40,None
1,7,4533,CASEY'S GENERAL STORE #1985 / ST. ANSGAR,ST ANSGAR,66,MITCHELL,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER LIQUEUR MINI MEISTERS,12,20,4.93,7.40,1,7.40,None
2,12,3723,J D SPIRITS LIQUOR,ONAWA,67,MONONA,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER LIQUEUR MINI MEISTERS,12,20,4.93,7.40,1,7.40,None
3,67,2614,HY-VEE #3 FOOD & DRUGSTORE / DAVENPORT,DAVENPORT,82,SCOTT,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER LIQUEUR MINI MEISTERS,12,20,4.93,7.40,1,7.40,None
4,85,4046,J AND K MARKET,CENTERVILLE,4,APPANOOSE,CANADIAN WHISKIES,10555,BLACK VELVET TOASTED CARAMEL,24,375,3.07,4.61,5,23.05,None
5,99,5268,THE DEPOT ATKINS,ATKINS,6,BENTON,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
6,160,2572,HY-VEE FOOD STORE / CEDAR FALLS,CEDAR FALLS,7,BLACK HAWK,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
7,165,3717,THE LIQUOR STOP / SUMNER,SUMNER,9,BREMER,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.60,5,23.00,None
8,166,2290,AL'S LIQUORS UNLIMITED,STORM LAKE,11,BUENA VISTA,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.60,5,23.00,None
9,171,2806,OSCO #881 / CLINTON,CLINTON,23,CLINTON,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
10,189,2616,HY-VEE FOOD AND DRUG / CLINTON,CLINTON,23,CLINTON,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.24,10.85,5,54.25,None
11,203,2616,HY-VEE FOOD AND DRUG / CLINTON,CLINTON,23,CLINTON,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
12,207,4873,CASEY'S GENERAL STORE #2559 / GRANGE,GRANGER,25,DALLAS,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
13,208,4898,BURLINGTON SHELL,BURLINGTON,29,DES MOINES,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,8.00,12.00,5,60.00,None
14,242,2506,HY-VEE #1044 / BURLINGTON,BURLINGTON,29,DES MOINES,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
15,266,4524,CASEY'S GENERAL STORE #1139 / NORA SPRINGS,NORA SPRINGS,34,FLOYD,CANADIAN WHISKIES,10805,CROWN ROYAL REGAL APPLE,24,375,8.00,12.00,5,60.00,None
16,294,4690,SUPER STOP AND SHOP / BALDWIN,BALDWIN,49,JACKSON,CANADIAN WHISKIES,10805,CROWN ROYAL REGAL APPLE,24,375,8.00,12.00,5,60.00,None
17,299,2517,HY-VEE FOOD STORE #1 / NEWTON,NEWTON,50,JASPER,CANADIAN WHISKIES,10624,CANADIAN CLUB WHISKY,24,375,4.28,6.42,5,32.10,None
18,300,2517,HY-VEE FOOD STORE #1 / NEWTON,NEWTON,50,JASPER,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
19,301,4604,PIT STOP LIQUORS / NEWTON,NEWTON,50,JASPER,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.65,11.48,5,57.40,None
20,354,2487,ANAMOSA FAMILY FOODS,ANAMOSA,53,JONES,CANADIAN WHISKIES,10624,CANADIAN CLUB WHISKY,24,375,4.28,6.42,5,32.10,None
21,376,2590,HY-VEE FOOD STORE #5 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
22,388,2552,HY-VEE FOOD STORE #3 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
23,392,5172,UPTOWN LIQUOR & TOBACCO,CEDAR RAPIDS,57,LINN,CANADIAN WHISKIES,10805,CROWN ROYAL REGAL APPLE,24,375,8.00,12.00,5,60.00,None
24,410,3403,ECON-O-MART / COLUMBUS JUNCTION,COLUMBUS JUNCTION,58,LOUISA,SCOTCH WHISKIES,5345,JOHNNIE WALKER RED,24,375,8.00,12.00,5,60.00,None
25,411,4362,KUM & GO #135 / POLK CITY,POLK CITY,77,POLK,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
26,456,4446,QUIK TRIP #513 / URBANDALE,URBANDALE,77,POLK,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
27,466,4368,KUM & GO #570 / JOHNSTON,JOHNSTON,77,POLK,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,8.00,12.00,5,60.00,None
28,489,4622,QUIK TRIP #544 / SE 14TH DM,DES MOINES,77,POLK,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,8.00,12.00,5,60.00,None
29,492,5057,KUM & GO #535 / DES MOINES,DES MOINES,77,POLK,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,8.00,12.00,5,60.00,None
30,530,4478,U S GAS,DES MOINES,77,POLK,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
31,554,4301,SAHOTA FOOD MART,DES MOINES,77,POLK,SCOTCH WHISKIES,5325,JOHNNIE WALKER BLACK,24,375,11.50,17.25,5,86.25,None
32,555,2587,HY-VEE FOOD STORE / JOHNSTON,JOHNSTON,77,POLK,SCOTCH WHISKIES,5345,JOHNNIE WALKER RED,24,375,7.50,11.24,5,56.20,None
33,556,2567,HY-VEE DRUGSTORE / DAVENPORT,DAVENPORT,82,SCOTT,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
34,557,3917,SMOKIN' JOE'S #2 TOBACCO AND LIQUOR OUTLET,DAVENPORT,82,SCOTT,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
35,558,4296,CIRCLE B MARKET,KEOSAUQUA,89,VAN BUREN,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
36,592,2621,HY-VEE FOOD STORE #3 / SIOUX CITY,SIOUX CITY,97,WOODBURY,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.65,11.48,5,57.40,None
37,593,5606,SA TOBACCO LIQUOR MART,CLINTON,23,CLINTON,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
38,628,2528,HY-VEE FOOD STORE #3 / DES MOINES,DES MOINES,77,POLK,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
39,650,5107,KUM & GO #4098 / WINDSOR HEIGHTS,WINDSOR HEIGHTS,77,POLK,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
40,652,2501,HY-VEE #2 / AMES,AMES,85,STORY,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
41,749,5065,CIRCLE S GORDON DRIVE,SIOUX CITY,97,WOODBURY,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
42,750,4454,KUM & GO #248 / SIOUX CITY,SIOUX CITY,97,WOODBURY,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
43,768,2201,HAPPY'S WINE & SPIRITS WHOLESALE,CEDAR FALLS,7,BLACK HAWK,CREAM LIQUEURS,73053,RUMCHATA,40,1000,17.00,25.50,18,459.00,None
44,801,3944,SAM'S CLUB 4973 / DUBUQUE,DUBUQUE,31,DUBUQUE,IMPORTED VODKAS,34422,GREY GOOSE,6,1000,22.75,34.13,18,614.34,None
45,806,5102,WILKIE LIQUORS,MOUNT VERNON,57,LINN,IMPORTED VODKAS,34422,GREY GOOSE,6,1000,19.00,28.50,18,513.00,None
46,807,5102,WILKIE LIQUORS,MOUNT VERNON,57,LINN,IMPORTED VODKAS,34422,GREY GOOSE,6,1000,22.75,34.13,18,614.34,None
47,828,3385,SAM'S CLUB 8162 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,STRAIGHT RYE WHISKIES,27175,TEMPLETON 4YR RYE,6,1000,21.00,31.50,18,567.00,None
48,891,4829,CENTRAL CITY 2,DES MOINES,77,POLK,IMPORTED DRY GINS,28627,HENDRICK'S GIN,6,1000,21.17,31.76,18,571.68,None
49,918,4829,CENTRAL CITY 2,DES MOINES,77,POLK,STRAIGHT BOURBON WHISKIES,22217,WOODFORD RESERVE,6,1000,26.49,39.74,18,715.32,None
50,962,4829,CENTRAL CITY 2,DES MOINES,77,POLK,STRAIGHT BOURBON WHISKIES,22217,WOODFORD RESERVE,6,1000,26.49,39.74,18,715.32,None
51,970,4312,I-80 LIQUOR / COUNCIL BLUFFS,COUNCIL BLUFFS,78,POTTAWATTAMIE,IMPORTED VODKAS,34422,GREY GOOSE,6,1000,22.75,34.13,18,614.34,None
52,971,2625,HY-VEE WINE & SPIRITS #2 / DAVENPORT,DAVENPORT,82,SCOTT,100% AGAVE TEQUILA,87511,1800 SILVER,6,1000,18.00,27.00,18,486.00,None

In [ ]:
#Menghapus data pada tabel sales dengan ketentuan bottles_sold kurang dari 20
query = """DELETE FROM sales
WHERE bottles_sold < 20;"""
kursor.execute(query)

In [ ]:
#Mengecek kembali data yang sudah diubah pada tabel sales dengan ketentuan bottles_sold kurang dari 20
pd.read_sql_query("""SELECT * FROM sales WHERE bottles_sold <20;""",koneksi)

Empty DataFrame
Columns: [index, store_number, store_name, city, county_number, county, category_name, item_number, item_description, pack, bottle_volume_ml, state_bottle_cost, state_bottle_retail, bottles_sold, sale_dollars, rating]
Index: []

# NO 6.5

In [ ]:
#Mengecek data pada tabel sales dengan ketentuan sale_dollars nya kurang dari 100 dan lebih dari 1000
pd.read_sql_query("""SELECT * FROM sales WHERE sale_dollars <100 OR sale_dollars >1000;""",koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,61,3494,SAM'S CLUB 6514 / WATERLOO,WATERLOO,7,BLACK HAWK,100% AGAVE TEQUILA,88296,PATRON SILVER,12,750,28.00,42.00,24,1008.00,None
1,135,5251,NORTHSIDE LIQUOR,MASON CITY,17,CERRO GORDO,100% AGAVE TEQUILA,89175,DON JULIO ANEJO,6,750,34.49,51.74,24,1241.76,None
2,187,3814,COSTCO WHOLESALE #788 / WDM,WEST DES MOINES,25,DALLAS,SINGLE MALT SCOTCH,4356,BALVENIE 12YR DOUBLEWOOD,12,750,32.50,48.75,24,1170.00,None
3,198,6242,WALL TO WALL WINE AND SPIRITS / WEST DES MOINES,WEST DES MOINES,25,DALLAS,IMPORTED CORDIALS & LIQUEURS,66056,NONINO AMARO QUINTESSENTIA,6,750,31.31,46.97,24,1127.28,None
4,320,2512,HY-VEE WINE AND SPIRITS / IOWA CITY,IOWA CITY,52,JOHNSON,100% AGAVE TEQUILA,87485,DON JULIO BLANCO,6,750,29.50,44.25,24,1062.00,None
5,603,2521,HY-VEE FOOD AND DRUG / GRAND / WDM,WEST DES MOINES,77,POLK,CORN WHISKIES,26613,FOUNDRY CORN WHISKEY,6,750,40.00,60.00,24,1440.00,None
6,617,2536,HY-VEE / PLEASANT HILL,PLEASANT HILL,77,POLK,AMERICAN VODKAS,36301,MCCORMICK 80PRF VODKA,12,50,4.13,6.20,360,2232.00,None
7,693,2478,PRAIRIE MEADOWS,ALTOONA,77,POLK,100% AGAVE TEQUILA,88296,PATRON SILVER,12,750,28.00,42.00,24,1008.00,None
8,872,4255,FAREWAY STORES #058 / ORANGE CITY,ORANGE CITY,84,SIOUX,TEMPORARY & SPECIALTY PACKAGES,13062,CROWN ROYAL W/ALTERNATE BAG,12,750,15.07,22.61,53,1198.07,None

In [ ]:
#Menghapus data pada tabel sales dengan ketentuan sale_dollars nya kurang dari 100 atau lebih dari 1000
query =""" DELETE FROM sales
WHERE sale_dollars <100 OR sale_dollars >1000;"""
kursor.execute(query)

In [ ]:
#Mengecek lagi data yang sudah diubah pada tabel sales dengan ketentuan sale_dollars nya kurang dari 100 atau lebih dari 1000
pd.read_sql_query("""SELECT * FROM sales WHERE sale_dollars <100 OR sale_dollars >1000;""",koneksi)

Empty DataFrame
Columns: [index, store_number, store_name, city, county_number, county, category_name, item_number, item_description, pack, bottle_volume_ml, state_bottle_cost, state_bottle_retail, bottles_sold, sale_dollars, rating]
Index: []

# CEK ISI KESELURUHAN ISI KOLOM SALES

In [ ]:
pd.read_sql_query("""SELECT * FROM sales;""", koneksi)

,index,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,0,5052,CASEY'S GENERAL STORE #3220 / GREENF,GREENFIELD,1,ADAIR,SPICED RUM,43025,ADMIRAL NELSON SPICED RUM PET,12,750,6.00,9.00,24,216.00,None
1,1,4317,FAREWAY STORES #941 / GREENFIELD,GREENFIELD,1,ADAIR,CANADIAN WHISKIES,10550,BLACK VELVET TOASTED CARAMEL,12,750,6.75,10.13,24,243.12,None
2,2,5052,CASEY'S GENERAL STORE #3220 / GREENF,GREENFIELD,1,ADAIR,CANADIAN WHISKIES,11786,BLACK VELVET TRAVELER,12,750,5.23,7.85,24,188.40,None
3,3,4472,QUICK SHOP FOODS / CENTERVILLE,CENTERVILLE,4,APPANOOSE,CANADIAN WHISKIES,11776,BLACK VELVET,12,750,5.23,7.85,24,188.40,None
4,5,5714,YESWAY #1031,CENTERVILLE,4,APPANOOSE,AMERICAN VODKAS,36304,MCCORMICK 80PRF VODKA,24,375,1.86,2.79,48,133.92,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933,995,3722,WAL-MART 1361 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,78293,MCCORMICK 80PRF VODKA,12,750,8.25,12.38,24,297.12,None
934,996,4197,FAREWAY STORES #014 / SERGEANT BLUFF,SERGEANT BLUFF,97,WOODBURY,AMERICAN VODKAS,38176,MCCORMICK 80PRF VODKA,12,750,10.00,15.00,24,400.00,None
935,997,2621,HY-VEE FOOD STORE #3 / SIOUX CITY,SIOUX CITY,97,WOODBURY,AMERICAN VODKAS,38176,MCCORMICK 80PRF VODKA,12,750,10.00,15.00,24,400.00,None
936,998,5388,KUM & GO #119/ NORTHWOOD,NORTHWOOD,98,WORTH,STRAIGHT BOURBON WHISKIES,17086,BULLEIT BOURBON,12,750,16.50,24.75,24,594.00,None
937,999,5287,YESWAY STORE # 1029/ CLARION,CLARION,99,WRIGHT,AMERICAN VODKAS,36305,MCCORMICK 80PRF VODKA,12,750,3.34,5.01,24,120.24,None